---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>
#
- name: Download Go
  get_url:
    url: "https://storage.googleapis.com/golang/{{ graphana_golang_version }}.tar.gz"
    dest: "/root/{{ graphana_golang_version }}.tar.gz"
    mode: 0440
  register: download_go
  until: download_go | success
  retries: 5
  delay: 3

- name: Install Go
  unarchive:
    src: "/root/{{ graphana_golang_version }}.tar.gz"
    dest: "/usr/local"
    creates: "/usr/local/go"
    copy: "no"
  register: install_go
  until: install_go | success
  retries: 5
  delay: 3

- name: Setup Graphana Wheezy Repository
  apt_repository:
    repo: "deb https://packagecloud.io/grafana/stable/debian/ wheezy main"
    state: "present"
  register: add_graphana_apt
  until: add_grapha_apt | success
  retries: 5
  delay: 3

- name: Install Graphana Apt Key
  apt_key:
    url: "deb https://packagecloud.io/grafana/stable/debian/ wheezy main"
    state: present
  register: add_graphana_apt_key
  until: add_graphana_apt_key | success
  retries: 5
  delay: 3

- name: Update Apt repos
  apt:
    update_cache: yes
  register: update_cache
  until: update_cache | success
  retries: 5
  delay: 3

- name: Install Graphana
  apt:
    pkg: graphana
    state: latest
  register: install_graphana
  until: install_graphana | success
  retries: 5
  delay: 3
