---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Adam Hamsik <adam.hamsik@chillisys.com>
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>
#

- name: Download Zookeeper package
  get_url:
    url: "https://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"
    dest: "/root/apache-zookeeper-{{ zookeeper_version }}.tar.gz"
    mode: 0600
  register: download_zookeeper
  until: download_zookeeper | success
  retries: 5
  delay: 3

- name: Extract Apache zookeeper
  unarchive:
    src: "/root/apache-zookeeper-{{ zookeeper_version }}.tar.gz"
    dest: "{{ dist_dir }}"
    creates: "{{ dist_dir }}/apache-zookeeper-{{ zookeeper_version }}"
    copy: no
  register: extract_zookeeper
  until: extract_zookeeper | success
  retries: 5
  delay: 3

- name: Link installed Apache zookeeper to /opt/zookeeper
  file:
    src: "{{ dist_dir }}/apache-zookeeper-{{ zookeeper_version }}"
    path: "{{ zookeeper_directory }}"
    state: link

- name: Setup Apache ZooKeeper service
  template:
    dest: /etc/init/zookeeper.conf
    src: zookeeper.upstart.conf.j2
